In [ ]:
import numpy as np

In [ ]:
a=np.random.seed(55)
a=np.random.randint(30,99,20)
a

array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [ ]:
a[-1]

79

In [ ]:
a[0]

32

In [ ]:
a.ndim

1

In [ ]:
a[19]

48

In [ ]:
b=np.random.randint(20,80,(8,9))
b

array([[27, 40, 33, 54, 36, 60, 39, 46, 34],
       [49, 20, 68, 62, 30, 67, 78, 77, 24],
       [46, 34, 26, 45, 26, 57, 71, 25, 69],
       [49, 43, 25, 63, 45, 55, 58, 70, 38],
       [58, 65, 52, 49, 76, 34, 37, 27, 38],
       [50, 61, 53, 68, 45, 21, 63, 30, 75],
       [69, 70, 33, 71, 79, 72, 22, 43, 44],
       [56, 55, 50, 70, 33, 34, 56, 24, 58]])

In [ ]:
b[1:5,1:6]

array([[20, 68, 62, 30, 67],
       [34, 26, 45, 26, 57],
       [43, 25, 63, 45, 55],
       [65, 52, 49, 76, 34]])

In [ ]:
b.shape

(8, 9)

In [ ]:
b.ndim

2

In [ ]:
b[2,0]

46

In [ ]:
b[2:6:1,1:7:1]

array([[34, 26, 45, 26, 57, 71],
       [43, 25, 63, 45, 55, 58],
       [65, 52, 49, 76, 34, 37],
       [61, 53, 68, 45, 21, 63]])

In [ ]:
array[row_start: row_end : row_step , col_start: col_end:col_step]

In [ ]:
import pandas as pd

In [ ]:
k=[[5,4],[3,2],[6,4],[5,3]]
k

[[5, 4], [3, 2], [6, 4], [5, 3]]

In [ ]:
t=np.array(k)
t

array([[5, 4],
       [3, 2],
       [6, 4],
       [5, 3]])

In [ ]:
t.ndim

2

In [ ]:
pd.Series(k)

0    5
1    4
2    3
3    2
4    4
5    5
6    3
dtype: int64

In [ ]:
t

array([[5, 4],
       [3, 2],
       [6, 4],
       [5, 3]])

In [ ]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     5    4
290     3    2
291     6    4
292     5    3

In [ ]:
df.columns

Index(['name', 'sub'], dtype='object')

In [ ]:
df['sub']

289    4
290    2
291    4
292    3
Name: sub, dtype: int64

In [ ]:
df['sub'].mean()

3.25

In [ ]:
df['sub'].median()

3.5

In [ ]:
df['sub'].mode()

0    4
Name: sub, dtype: int64

In [ ]:
df['sub'].var()

0.9166666666666666

In [ ]:
df['sub'].std()

0.9574271077563381

In [ ]:
df['sub'].max()

4

In [ ]:
df['sub'].min()

2